# Generated by Django 2.0.7 on 2019-04-19 20:06

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('data', django_mysql.models.ListCharField(models.IntegerField(), max_length=8800, size=800)),
            ],
        ),
    ]
